language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: eRkTCW6iKBJBt6OK4vXnidbN1wvuTlgVskMcnXkLl9MmvqYUu1vQWO9nfQI3vxDF8h9nwzfVdcLdYA1CBq5cQ5pi75phz1haFgxhronkpYgsDqOW6cg/+JmPC0Z/zYz1YYh0cWJOA3ocDXtWGvFzhFBygcjz6R1CtjSL1e4DwIlA1CC9XUQowJFMK1V5haACgbnBxJTi6jO9ulkcHaNKQxZkU1d6fgB0tb4Hfurgr1kH7oo3Ub5qRMb9ZX8HDbJqzr3YNL9qHrUml2faFkVjOSpWkAFCdxNC1UGo2rTdUv5DBxcHGgyJKejhT8JyPhvnMls5ydE8f63dkKWqNOkxJINcptPXrlSwpFHSLPBm/EOXT4wHm4bzwI2w+7yN2nvpywtvQROQlveZk57fHomeW2r8H9TOv2KEKYAo8gShxVteJqllK5g8MMWU33lkQROT6fgwUq0fDo4FCwe8pV2N2uhmk2O2IfX81GFuGGTgPNxd7nvIMgu9Z6doCfN59hgf2ZGZymF8lDOkK7CZFcpwIFCN42pH16IlnMJmjd3ackFLnBfs66pWN1o/f9DqB8Aich4/renfKi/G+jN/X4QpiudywUH3LlivhI84fn5fcxTKikEAhvSxssy/wRe3YQRc/384Ex5EyGtu18Ns3HZVlqecKwkZPwEKC2CqjiTvFpo=
  app: polar-ocean-88832
