language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: I6z8At5kdbacFhSVP8mjzbRGGzJSnQmpTUN9MmaV9IR32IcTvATK07PzkxbOPyQL70LAmtAzIr6VuvCEFKgyKeek+st7GA/I44ZMsXeOdZDNM24Ua7j5jLrCN3dlOoRcyLTVvVMCG6utjtYEjd+mzLmGuCH6irhX1NHBIxlnrrPYAA0am2Y1tNwOIEbkLqg0k2jttkhocap7v85M9Ng76I9kGqc0xWnPgnuVexGFS0bvaa7NsVkac4UEE2k9d3b1MZ9hIMz926+yKSm8YGoX2mIsghC9w1l7hvetUMn79CZgLA+CettWd707KU5CjCSL+g80YsYGIVDEVMSpu5pokonMBzDs0w6VkhVnyOgEfWYPiZW9fCV5VO5V+UwVM/xZbWDY6ilx2v3xOLS59G0kyaCqy9krjLFdrRBvtQd04KY/EB1pSTxRKe9WjFEdkWIpasiX3PbJeQO3L3huGWnmSzyjwlk2Lq/yjf6dA9QFhJN3mU6hf8PAByD8/1ZRhJZOH2qRtntkVSs31P0t7TXs2RAG/DvsZ4zbsEwb8BfMl1I2vTYDiV/Wj3041HKJLoAD11dQ7hTTt2WtTHa1C1sbCWCpsXRKqB6V8f2y2XJJpoaduLuWFLyK19ALjxgu+llKeEZdm6s1t+hbL2VDnJs46+dj3T6YYtlXgniU6Rks2Mw=
  app: polar-ocean-88832
