language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: QNW6/Yi4OBqzUTCMVcVxO5nlIagw+PGjI/PuscRkGNajLOYE6AfxrL2AqrLoF91+WNF7aaGAiaMwXR8JXAj5v1MmiSXEIl4lDcRu/M9AGRWvlwjTr0uuvv1vDy/bRqGlkVZRIyr8C6noicRrUhNGK3xpP64TrMSRexXqU6gtnGhNTFONTvhcu37tWXmHoDPMwMTLbgGHlwJpltVlIeLtElfSb8QTkpf2LuZne0hfTp2oNjO6c8sp/Iy+EMi/wXgQNBIFVzcw79eLydLPluKhviHFUErAqLL9fmAKjsW15IyhqDh/YCmX90DIaOMmKxkznHgk7n4cuiCShHGlA+SBQddcwiyNoR4bpOLNaoMrPjQzQ++An7mnf0HiOUHQhxsePmJfOm8qJzIC+onHMCKLlbHOEyu04NkYl/UA0ZDWJbeOi9Kh/v2TGXmLOTjMwS/UCtGgHeuZTCh3AkKc+gfohqoJNiqKQMb1A5ReJXbu/a9RKj7bg4fKyX1mUzp2gkv5pK7g9V/D7Q5XA+VzX//mUUNwoN7cSL7Yo2nLv88B8qCWfsV3SpKTrYoI97S/vByWH0Ajumt4MjsWTcY7o+VxdeIist+DRv3kGx4ksct1Hu7lsFO49EcZ8wYVsodq2AiAHCsO7qUD0u8K9nFGSl+2IKHhGYKJQxKHhmXmJsdhhA4=
  app: polar-ocean-88832
